FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/librawherey1-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8085
ENTRYPOINT ["java","-jar","demo.jar"]

#VOLUME /tmp
#EXPOSE 8085
#ARG JAR_FILE=target/librawherey1-0.0.1-SNAPSHOT.jar
#ADD ${JAR_FILE} app.jar
#ENTRYPOINT ["java","-jar","/app.jar"]